---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19838.
--- DateTime: 2022/10/11 12:48
---


lib996:include("Script/serialize.lua")

function npcclick_A(actor, npcid)
    --print("npcid",npcid)

    --Ò»¼üÂúÑª
    if npcid == 1 then
        yijianmanxue(actor)
    elseif npcid == 2 then
        kuangbaozhili(actor)
    elseif npcid == 3 then
        shachengjuanxian(actor)
    elseif npcid == 100 then
        ceshi(actor)
    end
end

GameEvent.add(EventCfg.onClicknpc, npcclick_A, "µã»÷npc")