---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/9/30 16:58
---

lib996:include("Script/serialize.lua")

function yijianmanxue(actor)
    lib996:release_print("yijianmanxue")
    lib996:humanhp(actor, "=", lib996:getbaseinfo(actor, ConstCfg.gbase.maxhp))
    lib996:humanmp(actor, "=", lib996:getbaseinfo(actor, ConstCfg.gbase.maxmp))
    lib996:sendmsg(actor, ConstCfg.notice.own,  '{"Msg":"<font color=\'#06c82e\'>״̬�ѻָ�</font>","Type":9}')
end
