---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/10/25 17:25
---

lib996:include("Script/serialize.lua")

function ceshi(actor)
    print(lib996:attr(actor, ConstCfg.attr.HP))
end
